### ISSUE TITLE
Syntax errors don't show details about actual error

### ISSUE THREAD

**Issue by atombender** [ForbesLindesay/browserify-middleware#40]
Any syntax error will just re-throw the exception, which will be coming from esprima.js, and break the server:

```
/node_modules/envify/node_modules/falafel/node_modules/esprima/esprima.js:3817
            throw e;
                  ^
Error: Line 17: Unexpected identifier
    at throwError (/node_modules/envify/node_modules/falafel/node_modules/esprima/esprima.js:1456:21)
    at throwUnexpected (/node_modules/envify/node_modules/falafel/node_modules/esprima/esprima.js:1500:13)
    at expect (/node_modules/envify/node_modules/falafel/node_modules/esprima/esprima.js:1523:13)
    at parseObjectInitialiser (/node_modules/envify/node_modules/falafel/node_modules/esprima/esprima.js:1740:17)
    at parsePrimaryExpression (/node_modules/envify/node_modules/falafel/node_modules/esprima/esprima.js:1810:20)
    at /node_modules/envify/node_modules/falafel/node_modules/esprima/esprima.js:3574:38
    at trackLeftHandSideExpressionAllowCall (/node_modules/envify/node_modules/falafel/node_modules/esprima/esprima.js:3478:61)
    at parsePostfixExpression (/node_modules/envify/node_modules/falafel/node_modules/esprima/esprima.js:1927:20)
    at /node_modules/envify/node_modules/falafel/node_modules/esprima/esprima.js:3574:38
    at parseUnaryExpression (/node_modules/envify/node_modules/falafel/node_modules/esprima/esprima.js:1997:16)
```

See https://github.com/substack/node-browserify/issues/308, for example.

**Comment by railrhoad** [comment]
I also see this same behavior here, unfortunately I'm not sure how to provide what you're looking for to help debug.  Essentially any error gets eaten with this exact error trace and I can't tell where to diagnose.
